name: schedmate
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # State management
  provider: ^6.1.2
  # Local storage
  shared_preferences: ^2.2.2
  # PDF and Excel export
  pdf: ^3.10.8
  excel: ^4.0.2
  path_provider: ^2.1.2
  # UI packages
  google_fonts: ^6.2.1
  flutter_material_design_icons: ^1.1.7296
  table_calendar: ^3.1.0
  # Internet connectivity
  connectivity_plus: ^5.0.2
  # Animation
  animated_splash_screen: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/logo.png
    - assets/logo/googlelogo.png
